export interface ILesson {
  id: string;
  classId: string;
  title: string;
  trimestre: number;
}

export const lessonsData: ILesson[] = [
  // Islamic
  { id: 'i01', classId: 'i', trimestre: 1,
    title: 'العقيدة في القرآن الكريم'
  },
  { id: 'i02', classId: 'i', trimestre: 1, 
    title: 'العقيدة الإسلامية وأثرها على الفرد والمجتمع' 
  },
  { id: 'i03', classId: 'i', trimestre: 1,
    title: 'وسائل القرآن الكريم في تثبيت العقيدة' 
  },
  { id: 'i04', classId: 'i', trimestre: 1,
    title: 'الإسلام والرسالات السماوية' 
  },
  { id: 'i05', classId: 'i', trimestre: 1,
    title: 'العقل في القرآن الكريم' 
  },
  { id: 'i06', classId: 'i', trimestre: 1,
    title: 'مقاصد الشريعة الإسلامي' 
  },
  { id: 'i07', classId: 'i', trimestre: 2,
    title: 'منهج الإسلام في محاربة الإنحراف والجريمة', 
  },
  { id: 'i08', classId: 'i', trimestre: 2,
    title: 'المساوات أمام أحكام الشريعة', 
  },
  { id: 'i09', classId: 'i', trimestre: 2,
    title: 'الصحة النفسية والجسمية في القرآن الكريم', 
  },
  { id: 'i10', classId: 'i', trimestre: 2,
    title: 'مصادر التشريع الإسلامي', 
  },
  { id: 'i11', classId: 'i', trimestre: 2,
    title: 'القيم في القرآن الكريم', 
  },
  { id: 'i12', classId: 'i', trimestre: 2,
    title: 'الوقف في الإسلام', 
  },
  { id: 'i13', classId: 'i', trimestre: 3,
    title: 'مدخل إلى علم الميراث والورثة وطرق ميراثهم', 
  },
  { id: 'i14', classId: 'i', trimestre: 3,
    title: 'الربا وأحكامه', 
  },
  { id: 'i15', classId: 'i', trimestre: 3,
    title: 'من المعاملات المالية الجائزة', 
  },
  { id: 'i16', classId: 'i', trimestre: 3,
    title: 'الحرية الشخصية ومدى ارتباطها بحرية الآخرين', 
  },
  { id: 'i17', classId: 'i', trimestre: 3,
    title: 'من أحكام الأسرة في الإسلام(النسب/التبني/الكفالة)', 
  },
  { id: 'i18', classId: 'i', trimestre: 3,
    title: 'العلاقات الإجتماعية بين المسلمين وغيرهم', 
  },
  { id: 'i19', classId: 'i', trimestre: 3,
    title: 'خطبة الرسول ﷺ حجة الوداع', 
  },

  // History 
  { id: 'h01', classId: 'h', trimestre: 123,
    title: 'تواريخ', 
  },
  { id: 'h02', classId: 'h', trimestre: 123,
    title: 'شخصيات تاريخ', 
  },
  { id: 'h03', classId: 'h', trimestre: 123,
    title: 'مصطلحات تاريخ', 
  },
  { id: 'h04', classId: 'h', trimestre: 1,
    title: 'بروز الصراع وتشكل العالم', 
  },
  { id: 'h05', classId: 'h', trimestre: 1,
    title: 'مساعي الإنفراج الدولي', 
  },
  { id: 'h06', classId: 'h', trimestre: 1,
    title: 'من الثنائية إلى الأحادية القطبية', 
  },
  { id: 'h07', classId: 'h', trimestre: 2,
    title: 'العمل المسلح ورد فعي الإستعمار', 
  },
  { id: 'h08', classId: 'h', trimestre: 2,
    title: 'استعادة السيادة الوطنية وبناية الدولة الجزائرية', 
  },
  { id: 'h09', classId: 'h', trimestre: 3,
    title: 'العالم الثالث بين تراجع الاستعمار التقليدي واستمرارية حركات التحرر', 
  },
  { id: 'h10', classId: 'h', trimestre: 3,
    title: 'فلسطين من تصفية الاستعمار التقليدي إلى الهيمنة الأحادية والتواطئ الدولي', 
  },

  // Geography
  { id: 'g01', classId: 'g', trimestre: 123,
    title: 'مصطلحات جغرافيا', 
  },
  { id: 'g02', classId: 'g', trimestre: 1,
    title: 'إشكالية التخلف والتقدم', 
  },
  { id: 'g03', classId: 'g', trimestre: 1,
    title: 'إشكالية المبادلات والتنقلات في العالم', 
  },
  { id: 'g04', classId: 'g', trimestre: 2,
    title: 'مصادر القوة للولايات المتحدة الأمريكية', 
  },
  { id: 'g05', classId: 'g', trimestre: 2,
    title: 'ظاهرة التكتل وأثرها في قوة الإتحاد الأوروبي', 
  },
  { id: 'g06', classId: 'g', trimestre: 3,
    title: 'العلاقة بين السكان والتنمية في شرق وجنوب شرق آسيا', 
  },
  { id: 'g07', classId: 'g', trimestre: 3,
    title: 'الاقتصاد الجزائري في العالم', 
  },
  { id: 'g08', classId: 'g', trimestre: 3,
    title: 'التنمية في البرازيل', 
  },

  // Philosophy
  { id: 'p01', classId: 'p', trimestre: 1,
    title: 'العلم والفلسفة', 
  },
  { id: 'p02', classId: 'p', trimestre: 1,
    title: 'المشكلة العلمية والإشكالية الفلسفية',
  },
  { id: 'p03', classId: 'p', trimestre: 1,
    title: 'أهمية الفلسفة',
  },
  { id: 'p04', classId: 'p', trimestre: 1,
    title: 'أصل الرياضيات حسي أم عقلي',
  },
  { id: 'p05', classId: 'p', trimestre: 1,
    title: 'هل الرياضيات مطلقة أم نسبية',
  },
  { id: 'p06', classId: 'p', trimestre: 1,
    title: 'مقارنة بين الرياضيات الكلاسيكية والمعاصرة',
  },
];
